---
title: Visualizations together — Community visualization challenges and their educational inspiration (Talk summary)
author: Amit Levinson
date: '2022-05-31'
slug: isvis-talk-post
categories: []
tags: []
subtitle: ''
summary: "Summarizing the things I love about and learned from data visualization challenges as part of a talk I gave at the Israeli visualization conference, 2022"
authors: []
lastmod: ''
featured: true
image:
  caption: ''
  focal_point: ''
  preview_only: true
projects: []
draft: true
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center')
```

```{css}
newcaption {
  font-size: 0.9em;
  text-align: center
}

.grayit {
  color: #A9A9A9;
  font-weight: normal;
}
```

A few weeks ago (May 12, 2022) I gave a talk about my experience in several data visualization challenges I took part in. It was a great experience summarizing what I took from these challenges and while you can find a recording of it, I thought I'd summarise it for those who enjoy reading.

I'll also take this opportunity to thank my wife — the night the call for talks closed I came to her and said "That's it, I'm not going to submit anything to ISVIS, I don't have anything to share". Luckily she convinced me otherwise, and this talk was born out of that process. Thank you.

## Data visualization challenges and their educational inspiration


[Figure about analyzing data in R]

I've actually come across data visualization challenges somewhat by chance. When I started thinking about MA thesis I realized I wanted to analyze it in something other than SPSS we learned, and came across the R programing language (also recommended by a friend). But I didn't want to wait for my thesis data to arrive, only to be incompetent to analyze it; rather, I wanted to be capale and confident in analyzing it. This is also how I thought about learning R — By manipulating and analyzing data, which eventually led me to data visualization challenges.

In the next couple of sections I'll share it was it I love about and learned from the challenges, and hope to motivate you to participate in an upcoming challenge.

### Community

Concurrent to wanting to learn R I also started roaming across Twitter. One day I came across the #TidyTuesday challenge, a data visualization challenge oriented to the R community. every week a new dataset is published and the R community is invited to analyze and visualize it. 

Observing for a few weeks I decided to participate in week 39, 2020. Doing a quick EDA I noticed a trend, somewhat intuitive, of an upward increase in the number of visitors to parks across years. Remembering a plot with added icons from the week before I adapted some of the code and produced my first plot. I posted it on Twitter and the feedback was amazing.

People were glad I joined, wanted to learn how I made the plot, added the icons and peak at my code (which took me a few hours to get onto GitHub. I was hooked on the project.

As time went by I joined additional projects such as the #30DayMapChallenge and #30DayChart challenge. In different from the #TidyTuesday, here you bring your own data. Additionally, the challenges occur through a whole month, where each day has its own theme and participants are invited to share maps/charts relating to that theme.

While the two challenges differ, I found a lot in common: Anyone and everyone are invited, beginners and advanced alike. Graph it in R, Python, Tableau, Qgis and whatnot. But most importantnly despite not knowing almost anyone I felt like I was part of a community.

[ gif community]


### Engaging

#### Meaningful data

#### Personal Data

### Learning

### <span class='grayit'>Learning</span> from others

### Learning 





<center>
`r blogdown::shortcode('tweet','1174364639427272706')` 
<newcaption>First visualization and participation in TidyTuesday</newcaption>
</center>  
