---
title: Dear visitor, help me decide - AB testing my own website.
author: Amit Levinson
date: '2021-06-10'
slug: ab-testing-my-website
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: ''
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: yes
draft: true
projects: []
---


The secrets in the Action:
[GitHub automatically creates a `GITHUB_TOKEN` secret to use in your workflow once you set up an Action](https://docs.github.com/en/actions/reference/authentication-in-a-workflow) in a repository. The token's permission are limited to the specific repository, but for our case it's adequate. 

BREAK

further adding of google analytics tags:
https://bash-prompt.net/guides/custom-html-jugo/

Site doesn't build from the public folder:
https://github.com/rstudio/blogdown/issues/495

If you find yourself getting weird commit requirements for stuff in the folder `resources` or `.Rporj.user` when just changing between branches then just gitignore them. This is defninitely not from professional knowledge, just my experience when searching for the issue online.

Essentially Hugo searches its [partials](https://gohugo.io/templates/partials/) (page templates such as header, footer, etc) in two places:

1. `layouts/partials/*<PARTIALNAME>.html` (We'll call this 'ours')  
2. `themes/<THEME>/layouts/partials/*<PARTIALNAME>.html` (We'll call this default)

If it won't find anything in our `layouts/partials`, it'll go to its default in the themes folder. My workflow is if I edit something, e.g. a site footer, I add it to my `layouts/partials`.  
Now, if you're like me, your probably just set up Google Analytics through your `config.toml`, specifically under `GoogleAnalytics = "UA-XXXXXXXXX-X"`.

When Hugo builds the site it parses all partials, and while parsing the `site_head.html` it'll [call the Google Analytics tag](https://github.com/AmitLevinson/amitlevinson.com/blob/e229045f6f90fe6221cddc6508743cfc8e269a1a/themes/hugo-academic/layouts/partials/site_head.html#L137-L138). More specifically, it runs:

```
{{ partial "marketing/google_analytics" . }}
{{ partial "marketing/google_tag_manager" . }}
```

What we want to do is edit the Google Analytics tag so it accounts for another branch. However, since I like to move any partials I edited from the themes, so I know in the future I've already edited it in the past, we'll just cut the `marketing` folder to our `partials/layout`. Now Hugo will render it from there and we'll know where to edit when we decide to stop the test.

After looking around for how to approach this, while trying some attempts for a Gatsby freamwork and not succedding, I came across a Hugo approach found here.


We'll add the following snippet (ADD IT):


==== 


### Conenct Google Anayltics to our branching system

Now we're going to connect our branching system to Google Analytics. Every time our page loads it renders either the branch or our main page. In our example there's a 50% chance someone will see a larger font and 50% chance they'll see a smaller font page. We want Google Analytics to recognize which branch the individual loaded so that it can be categorized accordingly to that branch.

To do that we create a 'custom dimension' under Google Analytics:

1. Click on Admin -> Custom definitions -> Custom dimensions -> New custom dimension.

2. Name however you like it, I use 'Branch' so that when Hugo returns whatever branch the site rendered it appears in that format. Leave the scope on Hit and Active checked (Which we'll remove later when we're finished).

In order to see the categorization by branch go to the main page's reports section, click on Behavior -> Site Content -> All page. In the middle you'll see a gray expandable box. We'll want to click that, scroll to Custom dimensions and click on the dimension we just created. It could take 24-48 hours until you see actual results so be patient if nothing happens (Trust me, this patience wasn't easy when testing how to do it).


