---
title: Using window functions after a GROUP BY clause
author: Amit Grinson
date: '2023-06-15'
layout: single
slug: window-function-with-groupby
categories: [SQL]
tags: [SQL, window]
subtitle: 'Leveraging window functions following a group by caluse'
summary: 'A short overview of how to use window functions within a group by query. Going over 3 examples that help illustrate how to combine the two, as well as a better understanding of order of opertaions in SQL'
featured: yes
projects: []
format: hugo-md
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, eval = TRUE)
```


```{r}
library(odbc)
library(DBI)

sqlconn <- dbConnect(odbc(),
                      Driver = "SQL Server",
                      Server = "localhost\\SQLEXPRESS",
                      Database = "window_groupby")
```

```{r, eval = FALSE}
payments <- read.csv('content/blog/window-function-with-groupby/payments.csv', colClasses = c('numeric', 'character', 'Date', 'numeric'))

dbWriteTable(conn = sqlconn, 'payments', payments, field.types = c(user_id = 'INT', payment_id = 'VARCHAR(12)',payment_date = 'DATE', amount = 'INT' ), overwrite = TRUE)

users <- read.csv('content/blog/window-function-with-groupby/users.csv')

dbWriteTable(conn = sqlconn, 'users', users, field.types = c(user_id = 'INT', country = 'VARCHAR(2)'), overwrite = TRUE)
```

### Intro


### Classic order by



### Ranking for additional filters



### New variables based on grouped outputs


```{r echo = FALSE}
dbDisconnect(sqlconn)
```

