---
title: Wrangling and Visualizing Data in R
authors: []
date: '2020-04-14T13:00:00'
publishdate: '2020-04-17'
event: 'Israel-2050 Passover holiday lectures'
event_url:
location: Zoom, Online
abstract: ''
categories: [talk]
tags: [talk]
subtitle: ''
summary: ' '
lastmod: '2019-06-17T18:00:01-07:00'
featured: no
image:
  caption: '[Image by Gerd Altmann from Pixabay]'
  focal_point: 'center'
  preview_only: no
projects: []
links:
- icon: images
  icon_pack: fas
  name: slides
  url: https://amitlevinson.github.io/slides-israel-2050/index.html#1
- icon: github
  icon_pack: fab
  name: code
  url: https://github.com/AmitLevinson/slides-israel-2050
---

R is an amazing tool for preparing and visualizing data. As political activists we want to provide our readers with information that will influence and motivate them to act. The talk outlines how I believe R can empower individuals to work with data in an efficient and aesthetic way.   
You can find a static example of knitting a document with parameters under the folder 'rmarkdown_eg' in the code repository. Rmarkdown's ability to render documents is something I found extremly advantageous over other programs such as SPSS, a statistical program commonly taught in the social science. The slides were given to a group of fellows of the program [Israel-2050](https://israel2050.co.il/) which I was a member of in 2017. This is not a hands-on learning session but an exposure to some of R's abilities I find fascinating and helpful for those wanting to work with data effectively.