---
title: The Joys of an unconventional Portfolio
authors: []
date: '2022-09-14T16:00:00'
publishdate: '2022-09-14'
event: 'Data TLV Summit'
event_url:
location: College of Management Academic Studies, Israel
abstract: ''
categories: [talk]
tags: [talk]
subtitle: ''
summary: ' '
lastmod: '2022-09-14T14:00:01-07:00'
featured: no
image:
  caption: ''
  focal_point: 'center'
  preview_only: yes
projects: []
links:
- icon: images
  icon_pack: fas
  name: slides
  url: https://amitlevinson.github.io/talks/tlv-summit/TLV_Summit.pdf
---



### Abstract

A personal portfolio can be a great resource to show your skills, especially when coming from a non-traditional background. But starting off with no real purpose you don’t necessarily treat it as a portfolio; rather just a place to hold your endeavors as you explore your curiosity.

In this talk I hope to share a few takeaways from creating an unconventional portfolio as I went into data analytics. Coming from a social science background and being introduced to programming I was suddenly able to answer questions that teased my curiosity. However, the translation of skills I gained from these projects wasn’t always clear to others and required me to bridge that gap, explaining what it is I took from these projects: For example, what is TF-IDF, the probability of winning the Israeli lottery and how they relate to communication? How did data visualization challenges prepare me for take home tests? What did playing around with GitHub Actions or a Raspberry Pi teach me about bots? Why would I want to explore distances to Golda ice-cream locations and lastly, why building a personal website was one of best decisions I made in my journey into data analytics.

<iframe src="https://amitlevinson.github.io/talks/tlv-summit/TLV_Summit.pdf" width = '100%' height='465px' frameborder="0"></iframe>
