<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.7.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Amit Levinson">

  
  
  
    
  
  <meta name="description" content="Analyzing tweets from the the Israeli elections week">

  
  <link rel="alternate" hreflang="en-us" href="/post/israeli-elections-on-twitter/">

  


  
  
  
  <meta name="theme-color" content="#3f51b5">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/zenburn.min.css" crossorigin="anonymous" title="hl-light">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/zenburn.min.css" crossorigin="anonymous" title="hl-dark" disabled>
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css" integrity="sha256-SHMGCYmST46SoyGgo4YR/9AlK1vf3ff84Aq9yK4hdqM=" crossorigin="anonymous">
    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,400i%7CKarla:400,700%7CRoboto+Mono&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  





<script async src="https://www.googletagmanager.com/gtag/js?id=UA-156329952-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
      dataLayer.push(arguments);
  }

  function trackOutboundLink(url) {
    gtag('event', 'click', {
         'event_category': 'outbound',
         'event_label': url,
         'transport_type': 'beacon',
         'event_callback': function () {
           document.location = url;
         }
    });
    console.debug("Outbound link clicked: " + url);
  }

  function onClickCallback(event) {
    if ((event.target.tagName !== 'A') || (event.target.host === window.location.host)) {
      return;
    }
    trackOutboundLink(event.target);  
  }

  gtag('js', new Date());
  gtag('config', 'UA-156329952-1', {});

  
  document.addEventListener('click', onClickCallback, false);
</script>


  


  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_hudc5a425b3e555d4faa8838526864126b_16079_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hudc5a425b3e555d4faa8838526864126b_16079_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="/post/israeli-elections-on-twitter/">

  
  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="twitter:site" content="@Amit_Levinson">
  <meta property="twitter:creator" content="@Amit_Levinson">
  
  <meta property="og:site_name" content="Amit Levinson">
  <meta property="og:url" content="/post/israeli-elections-on-twitter/">
  <meta property="og:title" content="Israeli elections on Twitter | Amit Levinson">
  <meta property="og:description" content="Analyzing tweets from the the Israeli elections week"><meta property="og:image" content="/images/icon_hudc5a425b3e555d4faa8838526864126b_16079_512x512_fill_lanczos_center_2.png">
  <meta property="twitter:image" content="/images/icon_hudc5a425b3e555d4faa8838526864126b_16079_512x512_fill_lanczos_center_2.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2020-04-20T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2020-04-20T00:00:00&#43;00:00">
  

  


    






  






<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "/post/israeli-elections-on-twitter/"
  },
  "headline": "Israeli elections on Twitter",
  
  "datePublished": "2020-04-20T00:00:00Z",
  "dateModified": "2020-04-20T00:00:00Z",
  
  "author": {
    "@type": "Person",
    "name": "Amit Levinson"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Amit Levinson",
    "logo": {
      "@type": "ImageObject",
      "url": "img//"
    }
  },
  "description": "Analyzing tweets from the the Israeli elections week"
}
</script>

  

  


  


  


  <title>Israeli elections on Twitter | Amit Levinson</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  







<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Amit Levinson</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Amit Levinson</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Blog</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#talks"><span>Talks</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      

      
      <li class="nav-item">
        <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
      </li>
      

      

    </ul>

  </div>
</nav>


  <article class="article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>Israeli elections on Twitter</h1>

  

  
    

    


<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
    
    Apr 20, 2020
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    15 min read
  </span>
  

  
  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder mr-1"></i><a href="/categories/r/">R</a></span>
  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style">
      


<div id="introduction" class="section level3">
<h3>Introduction</h3>
<p>Israel had its 3rd election within 12 months on March 2, 2020. This is because our Knesset - Hebrew term for house of representatives - wasn’t able to form or hold a government after each of the previous elections. As I won’t get into the politics of why they didn’t succeed in forming one (get it? politics 😉), I do want to take the opportunity and analyze some tweets posted in the time before and after the elections.<br />
When we think of a data aggregating tweets, many questions arise - who, what, when, where and more about our data. Namely, with the collected data I want to answer the following questions:</p>
<ol style="list-style-type: decimal">
<li>What was the frequency of tweets associated with the word ‘elections’?</li>
<li>Who tweeted the most?</li>
<li>What was the most common #Hashtag tweeted?</li>
<li>Which tweet was most liked and which was retweeted the most?</li>
<li>What were the most common words and bigrams (two words) in tweets?</li>
</ol>
</div>
<div id="gathering-the-data" class="section level3">
<h3>Gathering the data <i class="fab fa-twitter"></i></h3>
<p>Twitter’s API allows scraping <strong>6-9 days back for free</strong>. Therefore, I scraped the data already on March 7, 2020 and saved it for later use.</p>
<p>Let’s start with the packages we’ll use:</p>
<pre class="r"><code>library(rtweet)
library(tidyverse)
library(tidytext)
library(igraph)
library(hrbrthemes)
library(ggraph)
library(extrafont)</code></pre>
<p>I could use a consistent plot theme throughout the post but I’ll probably be editing each one a bit, while also some are not our regular graphs. With that said, There are some tweaks that will be consistent acorss several of the plots. Therefore, let’s create a theme function as a supplement to all other theme arguments I’ll use that will save a few lines of code:</p>
<pre class="r"><code>mini_theme &lt;- function(family = &quot;Roboto Condensed&quot;, tsize = 16) {
  theme_classic() +
  theme(text = element_text(family = family),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        plot.title = element_text(size = tsize))}</code></pre>
<p>Next we’ll gather the tweets we need:</p>
<pre class="r"><code>elections_raw &lt;- search_tweets(&quot;בחירות&quot;, n = 18000, retryonratelimit = TRUE)</code></pre>
<p>To gather the tweets we can use the <a href="https://rtweet.info/">{rtweet}</a> package which is amazing for collecting Twitter data. As I mentioned earlier, I already scraped the data a few days after the elections but left the command here to show what we did and how easy it is to do it. I searched only one term, ‘elections’ in Hebrew, and rtweet gathered all tweets containing that word.</p>
<p>What did our search yield? Let’s have a look:</p>
<pre class="r"><code>dim(elections)</code></pre>
<pre><code>## [1] 16560    90</code></pre>
<p>16,560 rows and 90 columns! As we can see, the <code>{rtweet}</code> package brings back a lot of information!</p>
<div id="some-caveats" class="section level4">
<h4>Some Caveats:</h4>
<p>Before we begin, I will say this post doesn’t aim to be representative of the discussions that were held during the election period. As a matter of fact, nor does it aim to be representative of the twitter discussions surrounding the elections. this is due to two main reasons:</p>
<ol style="list-style-type: decimal">
<li><p>Twitter isn’t common in Israel at all. I’m not sure what’s the usage rate but it’s definitely not representative of the Israeli population.</p></li>
<li><p>I searched for only one word - elections (in Hebrew) - which yielded some 16560 tweets. This is definitely not a large enough pool of tweets to claim for representation.</p></li>
</ol>
<p>With that said, the data gathered provides an opportunity to look at some Twitter data from the election period and motivate others to use the <code>{rtweet}</code> package, so why not give it a go.</p>
</div>
</div>
<div id="tweet-frequency" class="section level3">
<h3>Tweet frequency</h3>
<p>First, let’s see how the tweets distribute across the time span we searched for. we can create a quick time plot using the <code>ts_plot()</code> argument from the <code>{rtweet}</code> package:</p>
<pre class="r"><code>elections %&gt;% 
  ts_plot(&quot;2 hours&quot;)+
  geom_line(size = 1, color = &quot;black&quot;)+
  mini_theme()+
  scale_x_datetime(date_breaks = &quot;1 day&quot;,date_labels = &quot;%d %b&quot;)+
  labs(x= NULL, y = NULL,
       title = &quot;Tweet frequency throughout the Israeli elections week&quot;,
       subtitle = &quot;Tweets aggregated by two-hour interval. Only tweets containing the word &#39;elections&#39;\nin Hebrew were gathered&quot;)+
  geom_text(aes(x = as.POSIXct(&quot;2020-03-02 23:00:00&quot;), y = 435, label = &quot;10 PM:\nPolls close&quot;),
            hjust = 0, size = 3, family = &quot;Roboto Condensed&quot;)+
  geom_vline(xintercept = as.POSIXct(&quot;2020-03-02 22:00&quot;),linetype = &quot;dashed&quot;, size = 0.5, color = &quot;black&quot;, alpha = 5/10)+
  theme(plot.subtitle = element_text(color = &quot;gray70&quot;))</code></pre>
<p><img src="/post/elections-twitter/index_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Interesting - we see the number of tweets during the closing time is equivalent to that of midday on March 4th. Most of the votes were counted by the end of March 3rd, so I can’t really put my finger on what this jump represents. After all, I collected tweets containing our word so it could have been that many people tweeted that specific term in that time slot. Anyway, I wasn’t able to find anything interesting that happened on the news that day but feel free to explore and offer suggestions.</p>
</div>
<div id="users-with-most-tweets" class="section level3">
<h3>Users with most tweets</h3>
<p>Next, let’s look at who tweeted the most:</p>
<pre class="r"><code>elections %&gt;% 
  count(screen_name, sort = T) %&gt;% 
  slice(1:15) %&gt;% 
  mutate(screen_name = reorder(screen_name,n)) %&gt;% 
  ggplot(aes(x= screen_name, y= n))+
  geom_col(fill = &quot;gray70&quot;)+
  coord_flip()+
  scale_y_continuous(breaks = seq(0,180, 30), labels = seq(0,180,30))+
  labs(x = &quot;Screen name&quot;, y = &quot;Number of tweets&quot;, title = &quot;Top 15 users tweeting the word &#39;elections&#39;&quot;)+
  mini_theme()+
  theme(text = element_text(family = &quot;Calibri&quot;),
        axis.text = element_text(size = 12),
        axis.title.y = element_blank())</code></pre>
<p><img src="/post/elections-twitter/index_files/figure-html/unnamed-chunk-7-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>We see that many news companies tweeted a lot using the word ‘elections’: ‘newisrael13’, ‘kann_news’, ‘MaarivOnline’, ‘RotterNews’, ‘bahazit_news’, ‘RotterNet’. I personnaly don’t recognize the rest, but on the other hand I use Twitter mostly to follow <code>R</code> and academic related tweets, not necessarily Israeli politics.</p>
</div>
<div id="common-hashtags" class="section level3">
<h3>Common Hashtags</h3>
<p>When using the <code>{rtweet}</code> package to gather twitter data, one of the variables collected is the hashtags used in tweets. Although it doesn’t require too many lines of code to extract hashtags out of text, I think this is an amazing feature that shows the effort and details <a href="https://mikewk.com/">Michael W. Kearney</a> and contributors put into the package.</p>
<p>According to <a href="https://en.wikipedia.org/wiki/Hashtag">Wikipedia</a>, a ‘Hashtag’ “is a type of metadata tag used on social networks such as Twitter and other microblogging services.”, that basically tags the message with a specific theme. This helps to see trends and themes in a macro level.</p>
<p>OK then, let’s see what we have:</p>
<pre class="r"><code>hashtags &lt;- elections %&gt;% 
  select(hashtags) %&gt;% 
  unlist() %&gt;% 
  as.tibble() %&gt;% 
  mutate(value = tolower(value)) %&gt;% 
  count(value, name = &quot;Count&quot;, sort = T) %&gt;%
  mutate(value = reorder(value, Count),
         iscorona = ifelse(value == &quot;קורונה&quot; | value == &quot;coronavirus&quot;, &quot;y&quot;, &quot;n&quot;)) %&gt;% 
  filter(!is.na(value)) %&gt;% 
  slice(1:20)

ggplot(data = hashtags, aes(x = Count, y = value, fill = iscorona))+
  geom_col(show.legend = FALSE)+
  scale_fill_manual(values = c(y = &quot;#1DA1F2&quot;, n = &quot;gray70&quot;))+
  labs(y = NULL, x = &quot;Number of Tweets&quot;, title = &quot;Top 20 Hashtags addressing the Israeli elections&quot;)+
  mini_theme()+
  theme(text = element_text(family = &quot;Calibri&quot;),
        axis.text = element_text(size = 12))</code></pre>
<p><img src="/post/elections-twitter/index_files/figure-html/unnamed-chunk-9-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The tweets include pretty much what we expect - hashtags about the elections - with the two leading ones being ‘elections’ and ‘elections2020’. We also see a peculiar hashtag ‘right_following_right_people’, and others such as ‘Netanyahu’ (the Prime minister at the time), ‘Israel’ and others.<br />
I highlighted in blue an interesting hashtag at the time - <font color="#1DA1F2"><strong>Corona</strong></font> (in hebrew) and <font color="#1DA1F2"><strong>coronavirus</strong></font>. The elections were held on March 2, 2020, a little bit after the first cases reached Israel. Little did we know how it will affect us (I’m finalzing this post on April 18, 2020, and only now we’re starting to get back to routine. Slowly)</p>
</div>
<div id="most-liked-and-retweeted" class="section level3">
<h3>Most liked and retweeted</h3>
<p>Let’s have a look at which tweet was <strong>most liked</strong>. Twitter doesn’t define it as ‘likes’ but as ‘favorite’, or at least in the data that is collected through the <code>{rtweet}</code> package. Since I will want to gather the most of something - both favorite and later retweeted - I’ll create a function that will minimize re-writing the code.<br />
<br>
The function takes in a variable, reorders our dataset according to the variable we declared, extracts the first row and then pulls (extracts) the status id of that tweet. Lastly, the <code>blogdown::shortcode</code> enables to embed tweets, youtube videos and more into a blogdown post such as this, so we end the function by inserting our status id into that. For those just getting into functions notice that within the <code>arrange</code> argument we insert our variable in two curly brackets {{}}. This is a powerful feature of <code>{rlang}</code> when you want to manipulate a variable in a dataframe within a function. You can read more about that <a href="https://www.tidyverse.org/blog/2019/06/rlang-0-4-0/">here</a>.</p>
<pre class="r"><code>get_most &lt;- function(var){
elections %&gt;% 
  arrange(desc({{var}})) %&gt;% 
  .[1,] %&gt;% 
  pull(status_id) %&gt;% 
  blogdown::shortcode(&#39;tweet&#39;,.)
}</code></pre>
<p>Now Let’s see which tweet was <strong>most liked</strong> during that week:</p>
<center>
<blockquote class="twitter-tweet"><p lang="iw" dir="rtl">יותר מהכל, אני שמח שלא יהיו עוד בחירות בשביל המשפחה שלי שסבלה בגבורה שנה ורבע. רעות עברי וענר 😍</p>&mdash; עמית סגל Amit Segal (@amit_segal) <a href="https://twitter.com/amit_segal/status/1234584864415997952?ref_src=twsrc%5Etfw">March 2, 2020</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

</center>
<p>The tweet is by ‘Amit Segal’ - an Israeli news reporter - and it says (my translation):</p>
<blockquote>
<p>“More than anything, I’m glad there won’t be another elections for my family that suffered in honors a year and a quarter. Reut, Ivri and Aner 😍”</p>
</blockquote>
<p>Ha, interestingly he wrote it before the end of the elections, hopefully he’s right!</p>
<p>Now let’s look at the <strong>most re-tweeted</strong> tweet:</p>
<center>
<blockquote class="twitter-tweet"><p lang="iw" dir="rtl">אם ההקלטה של יועצו של גנץ מבושלת ושקרית (כדברי גנץ עכשיו), אז למה גנץ פיטר אותו?<br><br>יועצו של גנץ פוטר בגלל שאמר את האמת שכולם יודעים: גנץ לא יכול להיות ראש ממשלה. אנחנו כן. עוד 2 מנדטים לליכוד ואנחנו מוציאים את המדינה מהפלונטר, מונעים עוד בחירות ומקימים ממשלה</p>&mdash; Benjamin Netanyahu (@netanyahu) <a href="https://twitter.com/netanyahu/status/1233342393740603394?ref_src=twsrc%5Etfw">February 28, 2020</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

</center>
<p>The tweet is by Benjamin Netanyahu, at the time the prime minister of Israel, who writes:</p>
<blockquote>
<p>“If the recording of Gantz’s advisor is orcherstrated and fabricated (according to Gantz’s words just now), why did Gantz fire him? Gantz’s advisor was fired because he said the truth everyone knows: Gantz can’t be a prime minister. We can. 2 more mandates to the Likkud and we are taking the country out of the plonter, preventing another election and form a government”</p>
</blockquote>
<p>This came after the exposure of a secret recording of Gantz in a closed meeting, A few days before election day.</p>
</div>
<div id="wordcloud-and-bigrams" class="section level2">
<h2>Wordcloud and bigrams</h2>
<p>Let’s have a look at two more text-related analyses:</p>
<ol style="list-style-type: decimal">
<li>A word-cloud<br />
</li>
<li>Bigrams (two-words) from our text</li>
</ol>
<p>We could try out more algorthims but I’ll save them for a different post (feel free to try on your own).</p>
<div id="wordcloud" class="section level3">
<h3>Wordcloud</h3>
<p>In order to tackle the wordcloud, I’ll break up all the tweets into <strong>single words</strong>, filter any Hebrew stop words (file found online) and all English words. The decision to filter English words is mainly because I’m interested in the Hebrew sentences, but also because most the common English words used in our data are those of Twitter user names cited when replying to a tweet:</p>
<pre class="r"><code>he_stopwords &lt;- read_tsv(&quot;https://raw.githubusercontent.com/gidim/HebrewStopWords/master/heb_stopwords.txt&quot;, col_names = &quot;word&quot;)

election_token &lt;- elections %&gt;% 
  unnest_tokens(word, text) %&gt;% 
  select(word) %&gt;%
  anti_join(he_stopwords) %&gt;% 
  count(word, sort = T) %&gt;%
  filter(!grepl(&quot;([a-z]+|בחירות)&quot;, word), n&gt;= 150)</code></pre>
<p>Now we can create a wordcloud of words appearing more than 150 times using <code>{wordcloud2}</code> package<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>:</p>
<pre class="r"><code>wordcloud2::wordcloud2(election_token, color = &quot;#1DA1F2&quot;, shape = &quot;circle&quot;)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-13"></span>
<img src="wc.png" alt="Wordcloud excludes Hebrew stop words and the word 'elections'" width="550" />
<p class="caption">
Figure 1: Wordcloud excludes Hebrew stop words and the word ‘elections’
</p>
</div>
<p><br></p>
<p>What we can see is many of the words we’d expect: Political candidates, government, fourth (in the context of fourth elections), partis’ names and more. I’ll provide a more thorough discussion following our bigram plot below, as I believe it addresses many of the same words.</p>
</div>
<div id="common-bigrams" class="section level3">
<h3>Common Bigrams</h3>
<p>Like we did before, we can break up our text data into <strong>two word</strong> observations, also known as bigrams. In order to account for all combinations, we break up the sentence to fit all possible options. For example, assume we have the following sentence:</p>
<p>“Danny went to vote yesterday”</p>
<p>Using the <code>unnest_tokens</code> we’ll break the sentence into the following bigrams:</p>
<ol style="list-style-type: decimal">
<li>Danny went<br />
</li>
<li>went to<br />
</li>
<li>to vote<br />
</li>
<li>vote yesterday</li>
</ol>
<p>Which gives us all possible options. We will also include two columns consisting of the bigram broken up into single words. This will help in filtering out bigrams containing Hebrew stop words or English words. I’ll not run through the following code but instead will point you to <a href="http://varianceexplained.org/">David Ronbinson</a> &amp; <a href="https://juliasilge.com/">Julia Silge</a> <a href="https://www.tidytextmining.com/">‘Text Mining with R’ Book</a> for further reading.</p>
<pre class="r"><code>elec_bigram &lt;- elections %&gt;%
  select(text) %&gt;% 
  unnest_tokens(bigram, text, token = &quot;ngrams&quot;, n = 2) %&gt;%
  separate(bigram, into = c(&quot;word1&quot;, &quot;word2&quot;), sep = &quot; &quot;, remove = FALSE) %&gt;% 
  filter(!word1 %in% he_stopwords$word,
         !word2 %in% he_stopwords$word,
         !grepl(&quot;([a-z]+|בחירות)&quot;, bigram)) %&gt;% 
  count(word1, word2, sort = T) %&gt;% 
  slice(1:45) %&gt;%
  graph_from_data_frame()

p_arrow &lt;- arrow(type = &quot;closed&quot;, length = unit(.1, &quot;inches&quot;))

ggraph(elec_bigram, layout = &quot;fr&quot;)+
  geom_edge_link(aes(edge_alpha = n), arrow = p_arrow, end_cap = circle(.04, &quot;inches&quot;), show.legend = FALSE)+
  geom_node_point(color = &quot;lightblue&quot;, size = 3)+
  geom_node_text(aes(label = name), vjust = 1, hjust = 1, family = &quot;Calibri&quot;)+
  theme_void()+
  labs(title = &quot;Twitter text bigram&quot;)+
  theme(text = element_text(family = &quot;Calibri&quot;),
        plot.title = element_text(hjust = 0.5 , face = &quot;bold&quot;, size = 18))</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-15"></span>
<img src="/post/elections-twitter/index_files/figure-html/unnamed-chunk-15-1.png" alt="Word bigram excludes Hebrew stop words and the word 'elections'" width="672" />
<p class="caption">
Figure 2: Word bigram excludes Hebrew stop words and the word ‘elections’
</p>
</div>
<p><br></p>
<p><strong>How should we read this graph?</strong></p>
<p>First off, We only plotted the 45 most common bigrams (out of 100,000+). Every word is connected to another word with an arrow pointing to a given direction. The direction to which the arrow points is the way to read that bigram. In addition, bolder lines represent a higher frequency of that bigram throughout all our text.<br />
For example, on the bottom of our graph we see the number ‘2’ connected to the words ‘mandates’ and ‘campagin’. The direction of the arrow signals that we should read the bigram as ‘2 mandates’ and ‘2 campagins’.</p>
<p><strong>What does this all mean?</strong></p>
<ul>
<li><p>We have discussions regarding the <strong>number of chairs a govenrment will have (62/61/60/58)</strong> connected to mentions of the number of election campaigns (2/3) we had, discussions of a united and/or minimal government and the forming of one in general.</p></li>
<li><p>We see <strong>mentions of individuals</strong> such as “Benjamin Netanyahu”, “Amit Segal” (Both we discussed earlier), “Natan Eshel”, <strong>but no mention of the main candidate running against Netanyahu - “Benny Gantz”</strong>. That’s actually kind of odd, but more on that in a minute.<br />
</p></li>
<li><p>We also see mentions of political parties such as “Meretz”, “Gesher” and “Labor” who ran together this time around, “Otzma Yehudit”, “United Torah Judaism”, and the “Joint List”. <strong>There’s no mention of the two leading parties - “Kahol Lavan” &amp; “The Likkud”.</strong>, despite the mentioning of the latter’s leader.</p></li>
<li><p>Mentions of Netanyahu’s indicment and the personal law associated him.</p></li>
<li><p>Mentions I’d categorize as ‘other’ such as “Terrorist supporters”, “Will of the people”, “Fake news”, "Go vote’, etc.
<br></p></li>
</ul>
<p>Actaully, this turned out more interesting than I thought. Several questions arose while looking at it: Several words are missing such as the main parties names (Likkud &amp; Kahol-Lavan), The leading oponent running against Benjamin Netanyahu - Benny Gantz - and other questions such as with whom are specific terms associated. Before we close up I’ll look at one question that troubles me - <strong>Why doesn’t Gantz appear in our list</strong> 😱?</p>
<div id="benny-gantzs-disappearance" class="section level4">
<h4>Benny Gantz’s disappearance</h4>
<p>In order to see why Benny Gantz doesn’t appear in our bigram plot I’ll do the following: I’ll break the text into bigrams and filter to <strong>have only the bigrams containing the word Gantz</strong>. Once we have that we can see why he doesn’t appear in our bigram plot despite appearing in our wordcloud.<br />
Before I run the analysis and give you the answer think for a moment - What was the process of coming up with the bigram? If I chose only the 50 most frequent bigrams, why would a word that appears many times in our text not appear in our bigram list? Alternatively, did we filter anything along the way? Maybe even give the previous chunk another glance before I answer it.<br />
<br>
Let’s have a look:</p>
<pre class="r"><code>gantz &lt;-elections %&gt;%
  select(text) %&gt;% 
  unnest_tokens(bigram, text, token = &quot;ngrams&quot;, n = 2) %&gt;%
  separate(bigram, into = c(&quot;word1&quot;, &quot;word2&quot;), sep = &quot; &quot;, remove = FALSE) %&gt;% 
  filter(word1 %in% &quot;גנץ&quot; |
         word2 %in% &quot;גנץ&quot;,
         !grepl(&quot;([a-z]+|בחירות)&quot;, bigram))</code></pre>
<p>The code is similar to what we did earlier only this time we left <strong>bigrams that match the word we want</strong> - bigrams containing the word Gantz. Now that we have our list of bigrams, let’s look at the count of bigrams containing the word גנץ (‘Gantz’):</p>
<pre class="r"><code>gantz %&gt;% 
  count(bigram, sort = T)</code></pre>
<pre><code>## # A tibble: 978 x 2
##    bigram         n
##    &lt;chr&gt;      &lt;int&gt;
##  1 של גנץ       160
##  2 בני גנץ      138
##  3 גנץ לא        90
##  4 על גנץ        70
##  5 את גנץ        69
##  6 עם גנץ        61
##  7 אם גנץ        41
##  8 גנץ היה       25
##  9 גנץ או        19
## 10 גנץ ליברמן    19
## # ... with 968 more rows</code></pre>
<p><strong>AHA!</strong> Now I see what happened. The first bigram is a stop word and the word Gantz (‘Of Gantz’). The second bigram should have been included as it is Gantz’s full name - Benny Gantz, which appears 138 times.<br />
So, why has it been filtered? This is a great question which we can answer if we look at our stop words we initially used. Let’s see if it has the word בני (‘benny’ in Hebrew):</p>
<pre class="r"><code>he_stopwords %&gt;% 
  filter(word == &quot;בני&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   word 
##   &lt;chr&gt;
## 1 בני</code></pre>
<p>Yes it does. At the time of writing this blog post it leaves me in a dilemma - Should I change the stop words file I used to a different one or maybe create my own? Or should I continue as is? I think leaving it will teach me (and hopefully whoever read this far) a valuable lesson of always checking your stop words. In a different context the specific bigram wouldn’t have got me thinking, but here it didn’t make sense that our leading candidate was filtered, thus my inquire into what happened. In hebrew the word Benny also means ‘my son’, which I wouldn’t describe as a stop word but whoever made the dataset I guess did.</p>
<p>If you wish to give it a try yourself, you can find the data in the form of an <code>.rds</code> or smaller <code>.csv</code> (excludes list columns) in my <a href="https://github.com/AmitLevinson/amitlevinson.com/blob/master/content/post/elections-twitter">github repository</a>.</p>
<p>Well then, that’s all for now folks! <strong>And remember, make sure to validate your stop words dataset!</strong>
<br></p>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>The function <code>wordcloud2</code> we wrote wasn’t actually run because it renders an html object which distorts the post. Instead I used the webshot of our rendered html file, read more about that <a href="https://www.r-graph-gallery.com/196-the-wordcloud2-library.html">here</a>.<a href="#fnref1" class="footnote-back">↩</a></p></li>
</ol>
</div>

    </div>

    





<div class="article-tags">
  
  <a class="badge badge-light" href="/tags/rtweet/">rtweet</a>
  
  <a class="badge badge-light" href="/tags/tidytext/">tidytext</a>
  
</div>



<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/post/israeli-elections-on-twitter/&amp;text=Israeli%20elections%20on%20Twitter" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/post/israeli-elections-on-twitter/&amp;t=Israeli%20elections%20on%20Twitter" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Israeli%20elections%20on%20Twitter&amp;body=/post/israeli-elections-on-twitter/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/post/israeli-elections-on-twitter/&amp;title=Israeli%20elections%20on%20Twitter" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Israeli%20elections%20on%20Twitter%20/post/israeli-elections-on-twitter/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/post/israeli-elections-on-twitter/&amp;title=Israeli%20elections%20on%20Twitter" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>












  






  
  
  
    
  
  
  <div class="media author-card content-widget-hr">
    
      
      <img class="portrait mr-3" src="/authors/admin/avatar_hub71a408706e589f09faa92e611c4d1ab_121232_250x250_fill_q90_lanczos_center.jpg" alt="Photo of Amit Levinson">
    

    <div class="media-body">
      <h5 class="card-title"><a href="/">Amit Levinson</a></h5>
      <h6 class="card-subtitle">Sociology MA student</h6>
      <p class="card-text">I&rsquo;m an avid R user interested in R analysis, visualizations, drug markets and political participation.</p>
      <ul class="network-icon" aria-hidden="true">
  
    
    
    
    
    
    
    
    <li>
      <a href="mailto:amitlevinson1@gmail.com" >
        <i class="fa fa-envelope"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://twitter.com/Amit_Levinson" target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://github.com/AmitLevinson" target="_blank" rel="noopener">
        <i class="fab fa-github"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://www.linkedin.com/in/amit-levinson-b23851150" target="_blank" rel="noopener">
        <i class="fab fa-linkedin"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://amitlevinson.com/cv/" target="_blank" rel="noopener">
        <i class="ai ai-cv"></i>
      </a>
    </li>
  
</ul>

    </div>
  </div>









  
  



  </div>
</article>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js" integrity="sha256-1zu+3BnLYV9LdiY85uXMzii3bdrkelyp37e0ZyTAQh0=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/r.min.js"></script>
        
      

    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js" integrity="sha256-EErZamuLefUnbMBQbsEqu1USa+btR2oIlCpBJbyD4/g=" crossorigin="anonymous"></script>
    

    
    
    <script>const code_highlighting = true;</script>
    

    

    
    

    

    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
    
    
    
    <script src="/js/academic.min.e5c8525332f417fe3589df9a6b25b6c4.js"></script>

    






  
  
  <div class="container">
    <footer class="site-footer">
  
  <p class="powered-by">
    
      <a href="/privacy/"></a>
    
    
       &middot; 
      <a href="/terms/"></a>
    
  </p>
  
  
  
  


 <p class="powered-by">
    © Amit Levinson 2020 &middot; 

    Made in <a href="https://cran.r-project.org/" target="_blank" rel="noopener"><i class="fab fa-r-project"></i>
</a> with <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a><a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener"> Academic theme</a>
 &#183; <a href="https://www.r-bloggers.com/" target="_blank" rel="noopener">R-Bloggers</a>

    
    <span class="float-right" aria-hidden="true">
      <a href="#" class="back-to-top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
