---
title: Using a window function within a group by query in SQL
author: Amit Grinson
date: '2023-06-18'
layout: single
slug: window-functions-after-groupby
categories: [SQL]
tags: [SQL, Window]
subtitle: 'Playing around with window functions in a Group By Query'
summary: 'Experimenting with running various window functions within a SQL aggregation query. Using a few examples we learn about the two operations, highlighting the order of operations and some unintended uses of window functions'
featured: yes
projects: []
format: hugo-md
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, eval = TRUE)
```


<details>
<summary>Setting up a SQL connection in R</summary>

I write my blog using the [Rstudio IDE](https://posit.co/). Since we'll be writing SQL in this post, we need to set up a local SQL connection. We're basically connecting to our local RDBMS, here MSSQL, and to a database I setup earlier.

```{r}
library(odbc)
library(DBI)

sqlconn <- dbConnect(odbc(),
                      Driver = "SQL Server",
                      Server = "localhost\\SQLEXPRESS",
                      Database = "recursion")
```

We also need to load the data for this post to the database. It's only needed once and we can do it in R as follows:

```{r, eval = FALSE}
dat <- read.csv('content/blog/recursive-cte/payments.csv', colClasses = c('numeric', 'character', 'character', 'numeric', 'Date'))

dbWriteTable(conn = sqlconn, 'payments', dat, field.types = c(payment_id = 'INT', payer = 'VARCHAR(10)', 
                                                  receiver = 'VARCHAR(10)', amount = 'INT',
                                                  payment_date = 'DATE'), overwrite = TRUE)
```


</details>

```{r echo = FALSE}
dbDisconnect(sqlconn)
```

