---
title: The Tidytuesday project
author: Amit Levinson
date: '2019-09-22'
slug: the-tidytuesday-project
categories: []
tags: []
subtitle: ''
summary: 'Visualizations from the Tidytuesday project - A weekly data project intended to practice summarizing, arranging and visualizing data.'
authors: []
lastmod: ''
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: yes
projects: []
---
<script>
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
  }
</script>

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

### **What is TidyTuesday?**  

>*"A weekly data project aimed at the R ecosystem. As this project was borne out of the R4DS Online Learning Community and the R for Data Science textbook, an emphasis was placed on understanding how  to summarize and arrange data to make meaningful charts with ggplot2, tidyr, dplyr, and other tools in the tidyverse ecosystem. However, any code-based methodology is welcome - just please remember to share the code used to generate the results."*  

You can read more about it [here](https://github.com/rfordatascience/tidytuesday).

Basically, every week the R4DS community publishes a **new data set** where the R community (or any code-based methdogology) is welcome to **analyze** and **visualize** the data. 
When I started learning R I saw it as a great opportunity to practice plotting and analzying various datasets; it's what get me motivated and fascinated with R. Every week you're challenged with a new data set and get to see how others have analyzed it.  

Whenever I have some free time I like to join in and give it a go. If you're looking to get some practice or enjoy analyzing the same data set as others - Join the party, there's much to learn!  
</br>
